item {
    id: 1
    name: 'coke-1.5l'
}

item {
    id: 2
    name: 'coke-700ml'
}

item {
    id: 3
    name: 'coke-bottle-2l'
}

item {
    id: 4
    name: 'coke-bottle-2l-zero'
}

item {
    id: 5
    name: 'coke-bottle-2ll'
}

item {
    id: 6
    name: 'coke-bottle-300ml'
}

item {
    id: 7
    name: 'coke-bottle-700ml'
}

item {
    id: 8
    name: 'coke-can'
}

item {
    id: 9
    name: 'coke-can-classic'
}

item {
    id: 10
    name: 'coke-can-diet'
}

item {
    id: 11
    name: 'coke-can-energy'
}

item {
    id: 12
    name: 'coke-can-espresso'
}

item {
    id: 13
    name: 'coke-can-orange'
}

item {
    id: 14
    name: 'coke-can-zero'
}

item {
    id: 15
    name: 'coke-glass'
}

item {
    id: 16
    name: 'coke-glass-diet'
}

item {
    id: 17
    name: 'coke-light-bottle-300ml'
}

item {
    id: 18
    name: 'coke-zero-bottle-2l'
}

item {
    id: 19
    name: 'coke-zero-bottle-700ml'
}

item {
    id: 20
    name: 'gooday-large'
}

item {
    id: 21
    name: 'gooday-medium'
}

item {
    id: 22
    name: 'gooday-mediuml-choco'
}

item {
    id: 23
    name: 'gooday-small'
}

item {
    id: 24
    name: 'gooday-small-5'
}

item {
    id: 25
    name: 'gooday-small-butter'
}

item {
    id: 26
    name: 'gooday-small-choco'
}

item {
    id: 27
    name: 'lays-large'
}

item {
    id: 28
    name: 'lays-med'
}

item {
    id: 29
    name: 'lays-small'
}

item {
    id: 30
    name: 'lays-small-5'
}

item {
    id: 31
    name: 'pepsi-can'
}

item {
    id: 32
    name: 'pepsi-can-0'
}

item {
    id: 33
    name: 'pepsi-can-pack-2'
}

item {
    id: 34
    name: 'sprite-can'
}

item {
    id: 35
    name: 'thumbsup-glass'
}